# enable dependabot to automatically update dependency lib

version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
    allow:
      - dependency-type: production
    ignore:
      - dependency-name: "*flink*"
    assignees:
      - chengjundong
    target-branch: main